name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Setup Laravel Environment
        run: |
          cp .env.example .env
          mkdir -p storage/framework/{cache/data,sessions,views}
          mkdir -p bootstrap/cache
          chmod -R 775 storage bootstrap/cache

      - name: Install Node Dependencies
        run: npm i

      - name: Add Flux Credentials Loaded From ENV
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run Migrations
        run: php artisan migrate --env=testing --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      - name: Clear Laravel Caches
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear

      - name: Build Assets
        run: npm run build

      - name: Run Tests
        run: ./vendor/bin/pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
